### ISSUE TITLE
how to set release and architecture during creation of container

### ISSUE THREAD

**Issue by ashish1099** [lxc/ruby-lxc#31]
This fails
```c.create("centos", { "release" => "7", "arch" => "amd64" })````

with this Output
```./a.rb:6:in `create': can't convert Hash into String (TypeError)
	from ./a.rb:6:in `<main>'```

**Comment by ranjib** [comment]
```ruby
c.create("centos", nil, {},  0, %w(-r trusty -a amd64))
```
doc: http://www.rubydoc.info/gems/ruby-lxc/LXC/Container#create-instance_method
example: https://github.com/ranjib/chef-lxc/blob/master/lib/chef/provider/lxc.rb#L31

**Comment by ashish1099** [comment]
Thanks @ranjib
