### ISSUE TITLE
Capturing the exit status of commands inside the container

### ISSUE THREAD

**Issue by akshaykarle** [lxc/ruby-lxc#32]
I've been trying to find ways to capture the exit status of the commands runs inside the container. I had a look at #attach and #run_command but couldn't find a way to capture the exit status. I naively tried somethings like:
```ruby
container = LXC::Container.new('foo')
container.start
status = nil
container.attach(wait: true) do 
    status = system("false") 
    p status       #=> false
end
p status           #=> nil
```
Has anyone had this issue before? Any suggestions to get hold of the exit status?

**Comment by ranjib** [comment]
Have u tried returning $?.

I use shellout or popen3 API calls for this. You can also use pipes to
communicate , e.g.
https://github.com/ranjib/lxc-extra/blob/master/lib/lxc/extra.rb

**Comment by akshaykarle** [comment]
Thanks for the suggestion @ranjib. I tried to return `$?` from the block passed to attach but it doesn't seem to return the same value as `$?`. I've switched to using `IO.pipe` to return the exit status as a workaround for now. I think we can close this issue, but would be a good if the gem supported something like this though.
