### ISSUE TITLE
clone segfaults with the latest lxc release

### ISSUE THREAD

**Issue by rvalle** [lxc/ruby-lxc#34]
Hi!

Just update lxc form 1.1.2 to latest 1.1.4 and LXC::Container.clone is throwing segfault

I haven't look into this yet, but I just wanted to ask if ruby-lxc is compatible with lxc 1.1.4 before getting into it.

**Comment by tych0** [comment]
Try rebuilding the binding against 1.1.4; there was an ABI mismatch fixed in 1.1.3 that caused various issues, and this could be one of them.

**Comment by rvalle** [comment]
Ok, I see.

Just re-installing the GEM did the job. 

Thanks!
